### ISSUE TITLE
still works?

### ISSUE THREAD

**Issue by thesebastianf** [xsnrg/OpenHAB2-tools#4]
it broke my oh2 after some modifications in oh ... probably folder structure?

should it still work?

was my fav way to upgrade to latest mightly

**Comment by xsnrg** [comment]
It should still work.  I have not run it for a few weeks over the holidays, but will try it tonight and update as necessary.

**Comment by xsnrg** [comment]
OK, with the update to karaf 4.0.8 and some other changes, there are more files to worry about in the userdata folder.  In particular userdata/etc.  I created a pull request on a branch called 4 if you want to give it a try and give me your feedback.  It worked for me.

Thanks for the issue report!

**Comment by thesebastianf** [comment]
thanks !!
